# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import malepy.models


class Migration(migrations.Migration):

    dependencies = [
        ('malepy', '0002_auto_20180122_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='fake_testing',
            field=models.FileField(blank=True, null=True, upload_to=malepy.models.assignment_data_set_directory),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='folder',
            field=models.CharField(default='undecided', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='testing',
            field=models.FileField(blank=True, null=True, upload_to=malepy.models.assignment_data_set_directory),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='training',
            field=models.FileField(blank=True, null=True, upload_to=malepy.models.assignment_data_set_directory),
        ),
    ]
