# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import malepy.models


class Migration(migrations.Migration):

    dependencies = [
        ('malepy', '0003_auto_20180122_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_name',
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(default='my_file', upload_to=malepy.models.submitted_file_name),
        ),
    ]
