# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malepy', '0004_auto_20180122_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='measurement',
            field=models.CharField(default='Accuracy', max_length=50),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sorting',
            field=models.CharField(choices=[('Asc', 'Asc'), ('Desc', 'Desc')], default='Asc', max_length=4),
        ),
    ]
