# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malepy', '0005_auto_20180122_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
