# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malepy', '0006_assignment_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='shortcut',
        ),
    ]
