# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import malepy.models


class Migration(migrations.Migration):

    dependencies = [
        ('malepy', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ending',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='folder',
            field=models.CharField(default='new_folder', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='starting',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='training',
            field=models.FileField(upload_to=malepy.models.assignment_data_set_directory),
        ),
    ]
